# Generated by Django 5.2.16 on 2026-07-10 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("national_id", models.CharField(max_length=50)),
                ("passport_number", models.CharField(blank=True, max_length=50)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="applications/photos/"
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("current_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Somaliland", max_length=100)),
                ("parent_name", models.CharField(blank=True, max_length=150)),
                ("parent_phone", models.CharField(blank=True, max_length=30)),
                ("highest_education", models.CharField(max_length=150)),
                ("institution", models.CharField(max_length=200)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("graduate", "Graduate"),
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                ("skills", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                (
                    "motivation",
                    models.TextField(verbose_name="Why do you want this course?"),
                ),
                ("career_goals", models.TextField()),
                (
                    "hear_about",
                    models.CharField(
                        choices=[
                            ("social", "Social Media"),
                            ("website", "Website"),
                            ("friend", "Friend / Family"),
                            ("university", "University / School"),
                            ("event", "Event / Workshop"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/cv/"
                    ),
                ),
                (
                    "transcript",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/transcripts/"
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/certificates/"
                    ),
                ),
                (
                    "national_id_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/ids/"
                    ),
                ),
                ("declaration", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("admin_comments", models.TextField(blank=True)),
                (
                    "internal_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "draft_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="courses.course",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV"),
                            ("transcript", "Transcript"),
                            ("certificate", "Certificate"),
                            ("national_id", "National ID"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="applications/docs/")),
                ("label", models.CharField(blank=True, max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "application status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["email"], name="application_email_c09a19_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="application_status_1508e0_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["application_number"], name="application_applica_423097_idx"
            ),
        ),
    ]
