# Generated by Django 5.2.15 on 2026-06-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                            ("course_update", "Course Update"),
                            ("announcement", "General Announcement"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("all", "All Applicants"),
                            ("approved", "Approved Applicants"),
                            ("pending", "Pending Applicants"),
                            ("rejected", "Rejected Applicants"),
                            ("specific", "Specific Email"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-sent_at"],
            },
        ),
    ]
