# Generated by Django 5.2.16 on 2026-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="visit_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Public home visits (unique sessions) used for the learners counter.",
            ),
        ),
    ]
