# Generated by Django 5.2.15 on 2026-06-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("field_of_study", models.CharField(max_length=255)),
                ("graduation_year", models.PositiveIntegerField()),
                (
                    "preferred_schedule",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("weekend", "Weekend"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                ("motivation", models.TextField()),
                ("career_goals", models.TextField()),
                ("comments", models.TextField(blank=True)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
