# Generated by Django 5.2.15 on 2026-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Programming", "Programming"),
                            ("Web Development", "Web Development"),
                            ("Mobile Development", "Mobile Development"),
                            ("Graphic Design", "Graphic Design"),
                            ("Digital Marketing", "Digital Marketing"),
                            ("Artificial Intelligence", "Artificial Intelligence"),
                            ("Business Skills", "Business Skills"),
                            ("Entrepreneurship", "Entrepreneurship"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g. 8 weeks, 3 months", max_length=100
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        default="free",
                        max_length=10,
                    ),
                ),
                ("instructor", models.CharField(max_length=255)),
                ("seats", models.PositiveIntegerField(default=30)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="courses/"),
                ),
                ("requirements", models.TextField(blank=True)),
                (
                    "outcomes",
                    models.TextField(blank=True, help_text="Learning outcomes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
    ]
